# Generated by Django 4.2.8 on 2024-03-23 00:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="goers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="level",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                default="1vs1",
                max_length=13,
            ),
        ),
    ]
