# Generated by Django 4.2.8 on 2024-04-15 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0002_event_goers_alter_event_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "styles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="1vs1",
                        max_length=13,
                    ),
                ),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="tip_posters/"),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="tip_videos/"),
                ),
                ("contact_info", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("battle", "Battle"),
                            ("showcase", "Showcase"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
