# Generated by Django 4.2.8 on 2023-12-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0003_remove_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerprofile",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
    ]
