# Generated by Django 4.2.8 on 2024-07-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0004_alter_event_level_alter_tip_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_info_pics/"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_pics_carousel",
                        to="newColonFour.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="info_pics_carousel",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="newColonFour.eventimage"
            ),
        ),
    ]
