# Generated by Django 4.2.8 on 2023-12-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0004_organizerprofile_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerVerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("processed", models.BooleanField(default=False)),
                (
                    "organizer_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newColonFour.organizerprofile",
                    ),
                ),
            ],
        ),
    ]
