# Generated by Django 4.2.8 on 2024-01-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0005_organizerverificationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizerprofile",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
