# Generated by Django 4.2.8 on 2024-07-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0005_eventimage_event_info_pics_carousel"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="info_pics_carousel",),
        migrations.AlterField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_pics_carousel",
                to="newColonFour.event",
            ),
        ),
    ]
