# Generated by Django 4.2.8 on 2024-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0007_organizerprofile_instagram_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="dancer",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
