# Generated by Django 4.2.8 on 2024-01-19 11:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0008_event_organizer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newColonFour.event",
                    ),
                ),
            ],
            bases=("newColonFour.event",),
        ),
        migrations.CreateModel(
            name="Showcase",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newColonFour.event",
                    ),
                ),
            ],
            bases=("newColonFour.event",),
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="newColonFour.event",
                    ),
                ),
            ],
            bases=("newColonFour.event",),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="styles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_hidden",
            field=models.BooleanField(default=True),
        ),
    ]
