# Generated by Django 4.2.8 on 2024-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0008_dancer_instagram_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="battle", name="host",),
        migrations.AddField(
            model_name="battle",
            name="host",
            field=models.ManyToManyField(
                blank=True, related_name="battle_hosts", to="newColonFour.dancer"
            ),
        ),
    ]
