# Generated by Django 4.2.8 on 2024-01-23 21:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0009_battle_showcase_workshop_event_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(
                        choices=[("USA", "United States"), ("CAN", "Canada")],
                        max_length=3,
                    ),
                ),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="dancer_pics/"),
                ),
                (
                    "styles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        related_name="dancers", to="newColonFour.event"
                    ),
                ),
            ],
        ),
    ]
