# Generated by Django 4.2.8 on 2024-01-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0010_dancer"),
    ]

    operations = [
        migrations.AddField(
            model_name="dancer",
            name="dancer_has_consented",
            field=models.BooleanField(default=False),
        ),
    ]
