# Generated by Django 4.2.14 on 2024-07-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0011_event_end_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="end_time",),
    ]
