# Generated by Django 4.2.8 on 2024-01-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0011_dancer_dancer_has_consented"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="newColonFour.dancer",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="is_7tosmoke",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="battle",
            name="judges",
            field=models.ManyToManyField(
                blank=True, related_name="battle_judges", to="newColonFour.dancer"
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="type",
            field=models.CharField(
                choices=[
                    ("1vs1", "1vs1"),
                    ("2vs2", "2vs2"),
                    ("3vs3", "3vs3"),
                    ("crew", "Crew"),
                ],
                default="1vs1",
                max_length=10,
            ),
        ),
    ]
