# Generated by Django 4.2.8 on 2024-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0012_battle_host_battle_is_7tosmoke_battle_judges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="level",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                default="1vs1",
                max_length=13,
            ),
        ),
    ]
