# Generated by Django 4.2.8 on 2024-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0014_alter_event_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_point",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
