# Generated by Django 4.2.8 on 2024-03-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0015_event_location_point"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="number_of_interests", new_name="goings",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="number_of_organizer_interests",
            new_name="number_of_goings",
        ),
    ]
