# Generated by Django 4.2.15 on 2024-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newColonFour", "0015_alter_tip_event_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="event_start_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
