COUNTRY_CHOICES = [
    # North America
    ('🇺🇸', 'United States'),
    ('🇨🇦', 'Canada'),
    ('🇲🇽', 'Mexico'),
    ('🇬🇹', 'Guatemala'),
    ('🇭🇹', 'Haiti'),
    ('🇧🇿', 'Belize'),
    ('🇨🇷', 'Costa Rica'),
    ('🇸🇻', 'El Salvador'),
    ('🇭🇳', 'Honduras'),
    ('🇳🇮', 'Nicaragua'),
    ('🇵🇦', 'Panama'),
    ('🇨🇺', 'Cuba'),
    ('🇩🇴', 'Dominican Republic'),
    ('🇯🇲', 'Jamaica'),
    ('🇧🇸', 'Bahamas'),
    ('🇧🇧', 'Barbados'),
    ('🇹🇹', 'Trinidad and Tobago'),

    # Europe
    ('🇬🇧', 'United Kingdom'),
    ('🇫🇷', 'France'),
    ('🇩🇪', 'Germany'),
    ('🇮🇹', 'Italy'),
    ('🇪🇸', 'Spain'),
    ('🇵🇹', 'Portugal'),
    ('🇳🇱', 'Netherlands'),
    ('🇧🇪', 'Belgium'),
    ('🇨🇭', 'Switzerland'),
    ('🇦🇹', 'Austria'),
    ('🇸🇪', 'Sweden'),
    ('🇳🇴', 'Norway'),
    ('🇩🇰', 'Denmark'),
    ('🇫🇮', 'Finland'),
    ('🇮🇸', 'Iceland'),
    ('🇮🇪', 'Ireland'),
    ('🇵🇱', 'Poland'),
    ('🇨🇿', 'Czech Republic'),
    ('🇸🇰', 'Slovakia'),
    ('🇭🇺', 'Hungary'),
    ('🇷🇴', 'Romania'),
    ('🇧🇬', 'Bulgaria'),
    ('🇬🇷', 'Greece'),
    ('🇹🇷', 'Turkey'),
    ('🇷🇺', 'Russia'),
    ('🇺🇦', 'Ukraine'),
    ('🇧🇾', 'Belarus'),
    ('🇱🇹', 'Lithuania'),
    ('🇱🇻', 'Latvia'),
    ('🇪🇪', 'Estonia'),
    ('🇲🇹', 'Malta'),
    ('🇨🇾', 'Cyprus'),
    ('🇱🇺', 'Luxembourg'),
    ('🇲🇨', 'Monaco'),
    ('🇱🇮', 'Liechtenstein'),
    ('🇸🇲', 'San Marino'),
    ('🇦🇩', 'Andorra'),
    ('🇻🇦', 'Vatican City'),
    ('🇷🇸', 'Serbia'),
    ('🇲🇪', 'Montenegro'),
    ('🇲🇰', 'North Macedonia'),
    ('🇦🇱', 'Albania'),
    ('🇧🇦', 'Bosnia and Herzegovina'),
    ('🇽🇰', 'Kosovo'),
    ('🇸🇮', 'Slovenia'),
    ('🇭🇷', 'Croatia')
    # Add more countries as needed
]
